StackVista/stackstate-process-agent

agent/collector.go
bootstrap.sh

Do not parse the return message from stackstate, to avoid getting errors.

Fix error message when data is not returned

---

checks/net.go
config/config.go
config/yaml_config.go
glide.lock
glide.yaml

Integration of in-flight connection work of tcptracer-bpf see https://github.com/StackVista/tcptracer-bpf/pull/4

Bump tcptracer to include in-flight connections

---

.gitlab-ci.yml
packaging/publish_staging_package.sh

Once this branch is merged, circleci build needs to be disabled, as it does parallel job

Cron builds

---

.gitlab-ci.yml

Fixes build by clearing shared gopath/pkg on job start

clear pkgs on start

---

checks/checks.go
checks/container.go
checks/container_nolinux.go
checks/container_rt.go
checks/container_rt_nolinux.go
checks/net.go
checks/process.go
checks/process_rt.go
cmd/agent/collector.go
cmd/agent/features/features.go
cmd/agent/main_common.go
config/config.go
config/config_test.go
config/yaml_config.go

Add feature flag interpretation from StackState

Add feature flags

---

.gitlab-ci.yml

Fixes nightly build docker stage.

improve(pipeline) adjusted docker configuration

---

checks/net_linux.go
checks/net_windows.go

Stac 11445: Error message

---

checks/net_common.go
checks/net_linux.go
checks/net_linux_test.go
checks/net_test.go
config/config.go
config/config_test.go
config/yaml_config.go

retry network tracer init

---

checks/process_common.go
checks/process_test.go

check if tags removal works

---

packaging/version.sh
stackstate-changelog.md

STAC-0 Fix tag discovery

---

config/config.go
config/config_test.go
config/yaml_config.go

STAC-13016: Enable both containerChecks and processChecks if proccess_config.enabled

---

config/config.go
config/config_test.go
config/yaml_config.go

This reverts commit 42bf8cfc62173f72718c5dea24e970357862dbc1, reversing
changes made to 22c410abecca36dc1577158f82b31d4955dbd925.

Revert "Merge pull request #73 from StackVista/STAC-13016"

---

.gitignore
Gopkg.lock
Gopkg.toml

STAC-11588: Ensure processes get namespace

---

Gopkg.lock
Gopkg.toml
checks/net_linux.go
conf-dev.yaml
config/config.go
config/config_test.go
config/yaml_config.go

STAC-13132 Protocol inspection flag

---

Gopkg.lock
Gopkg.toml

STAC-13066 Add support to IPv6 on HTTP metrics

---

config/config.go

STAC-13308 Protocol inspection envvar

---

config/config.go

STAC-13308 Fix STS_PROTOCOL_INSPECTION_ENABLED

---

DEVELOPMENT.md
Rakefile
Vagrantfile
bootstrap.sh
conf-dev.yaml
config/config_test.go
config/yaml_config.go
packaging/publish_image.sh
stackstate-changelog.md

https://stackstate.atlassian.net/browse/STAC-15225

Stac 15225 skip ssl option

---

DockerFiles/agent/stackstate-docker.yaml
config/config.go
config/config_test.go

Stac 15661 increase check intervals

---

.gitlab-ci.yml
README.md

Fix release_image job image

---

.gitlab-ci.yml
Rakefile
packaging/commit-or-tag.sh

Stac 0 fix tag version

---

.gitlab-ci.yml
DockerFiles/agent/Dockerfile
DockerFiles/agent/entrypoint/init-process.sh
config/config.go
packaging/publish_image.sh
verify-or-create-topics.sh

STAC-15220 process agent container

---

.cd-builders/runner-gitlab-centos7/Dockerfile
.gitlab-ci.yml
DockerFiles/local_builder/Dockerfile
DockerFiles/local_builder/local_init.sh
Makefile
Rakefile
go.mod
go.sum
stackstate-changelog.md

STAC-17765 Build agent on go 1.16

---

cmd/agent/main_docker.go

Signed-off-by: Juliano Krieger <julianosk@gmail.com>

STAC-17982: Ignore syscall signals

---

.gitlab-ci.yml

Signed-off-by: Juliano Krieger <julianosk@gmail.com>

STAC-0: Fix windows pre-release job

---

cmd/agent/main_common.go
config/config.go
config/config_test.go
config/yaml_config.go
docker-compose.yaml
go.mod
go.sum
pkg/config/config.go
stackstate-docker-dev.yaml

Stac 0 config fixes

---

.gitlab-ci.yml

STAC-18511 Remove Windows jobs (make manual).

---

DockerFiles/agent/stackstate-docker.yaml
config/config_nix.go
config/config_test.go

kubelet blacklist for k8s and openshift

---

.gitlab-ci.yml
packaging/publish_image.sh

STAC-19061 Changes for k8s-focused version of agent (images and tags).

---

.gitlab-ci.yml

Fixed linux deb package publishing

---

cmd/agent/main_common.go
config/config.go
config/config_test.go
config/dd_config.go
config/yaml_config.go

STAC-19382

---

config/yaml_config.go

STAC-19382 Force rebuild

---

checks/net.go
config/config.go
go.mod
go.sum
prebuild-datadog-agent-scripts/run-datadog-agent-prebuild.sh
prebuild-datadog-agent-scripts/run-datadog-agent-test.sh
prebuild-datadog-agent.sh

STAC-19417: Add container support from upstream

---

go.mod
go.sum

STAC-20043: Bump upstream datadog

---

go.mod
go.sum
prebuild-datadog-agent-scripts/run-datadog-agent-test.sh
prebuild-datadog-agent.sh

STAC-20043: Bump dependency

---

checks/net.go
checks/net_common.go
checks/net_test.go

STAC-20176: Additional metrics for the connection check

---

pkg/pods/pods.go

STAC-20190: Do not cache containers with empty id

---

config/config.go
config/config_test.go
config/tracer_config.go
config/yaml_config.go
go.mod
go.sum
prebuild-datadog-agent-scripts/run-datadog-agent-prebuild.sh

STAC-20521: Add config options for probe logging

---

.gitignore
.idea/.gitignore
.idea/codeStyles/Project.xml
.idea/codeStyles/codeStyleConfig.xml
.idea/misc.xml
.idea/modules.xml
.idea/sbt.xml
.idea/stackstate-process-agent.iml
.idea/vcs.xml

STAC-0: Add intellij setup

---

go.mod
go.sum
prebuild-datadog-agent.sh
update-datadog-dependency.sh

STAC-20143: Update upstream

---

go.mod
go.sum
prebuild-datadog-agent.sh

STAC-20593: Enable runtime compilation tests

---

Dockerfile
config/tracer_config.go
go.mod
go.sum
prebuild-datadog-agent-scripts/run-datadog-agent-test.sh

Stac 20593: wrap up work

---

.idea/inspectionProfiles/Project_Default.xml
Rakefile
prebuild-datadog-agent-scripts/run-datadog-agent-test.sh
prebuild-datadog-agent.sh

STAC-20605: Enable mongodb classification tests

---

.venv
checks/net.go
checks/net_test.go
config/tracer_config.go
go.mod
go.sum
prebuild-datadog-agent-scripts/run-datadog-agent-test.sh
prebuild-datadog-agent.sh
update-datadog-dependency.sh

STAC-20605: Support for MongoDB metrics

---

DockerFiles/agent/stackstate-docker.yaml

STAC-20704: Blacklist kubelet on gke

---

checks/net.go
config/tracer_config.go
go.mod
go.sum
prebuild-datadog-agent-scripts/run-datadog-agent-test.sh

STAC-20764: AMQP basics

---

checks/net.go

STAC-0: Fix reporting observations

---

checks/net.go

STAC-0: Do not produce 0 metrics for amqp

---

cmd/agent/collector.go

https://stackstate.atlassian.net/browse/STAC-21083

STAC-21083: Less logs

---

checks/checks.go
checks/net.go
checks/net_linux.go
checks/process.go
cmd/agent/collector.go
cmd/agent/main_common.go
config/tracer_config.go

STAC-0: Disable netlink connection tracking

---

go.mod
go.sum

STAC-21549: Bump agent upstream

---

go.mod
go.sum

STAC-21625: Bump dependency

---

config/tracer_config.go

STAC-21562: Enable netlink conntrack for cilium

---

go.mod
go.sum

STAC-21765: Integrate fix for net_dev_queue->skbaddr offset

---

cmd/agent/collector.go
cmd/agent/healthstate.go

STAC-21839: Bind health states to nodes and drop agent topology

---

.gitlab-ci.yml
go.mod

STAC-21888 Attempted go stl cve fixes.

---

.gitlab-ci.yml

STAC-21888 Merged build image to main branch, update image tag.

---

go.mod
go.sum

STAC-21883: Bump upstream to fix containerd mounting

---

.cerberus/cerberus_block_merges.sh
.cerberus/cerberus_notify_failure.sh
.gitlab-ci-arm.yml
.gitlab-ci.yml

STAC-21872: Add cerberus message on master pipeline failure

---

go.mod
go.sum

STAC-22744: Bump dependency after fixes for linux 5.4

---

README.md
checks/net.go
checks/net_postgres_test.go
go.mod
go.sum
model/message.go
model/message_test.go
test-server/.gitignore
test-server/README.md
test-server/config.go
test-server/config.json
test-server/main.go
test-server/main_test.go

[STAC-22553] Expose postgres tags

---

DockerFiles/agent/stackstate-docker.yaml
config/config.go
config/config_nix.go
config/config_test.go

STAC-0: Add k3s to process agent blacklist

---

go.mod
go.sum

chore: bump datadog dependency

---

checks/net.go
cmd/agent/main_common.go
cmd/agent/mem_watcher.go
go.mod
go.sum
test-server/Dockerfile

[stac-22939] fix: remove a memory leakage in `initialConnections` map

---

checks/process_common.go
checks/process_test.go
conf-dev.yaml

cleanup: turn a warning into an info log
